from OpenGL.GLU import *
from OpenGL.GL import *
from OpenGL.GLUT import *
from numpy import *
def rectangle(x, y, x1, y1, x2, y2, x3, y3, r, g, b, typ):
    glColor(r, g, b)
    glBegin(typ)
    glVertex2d(x, y)
    glVertex2d(x1, y1)
    glVertex2d(x2, y2)
    glVertex2d(x3, y3)
    glEnd()
def circle(rs, s, e, xnaught, ynaught, r, g, b, typ):
    glColor(r, g, b)
    glBegin(typ)
    for theta in arange(s, e, 0.01):
        x = rs * cos(theta) + xnaught
        y = rs * sin(theta) + ynaught
        glVertex2d(x, y)
    glEnd()
def triangle(x1, y1, x2, y2, x3, y3, r, g, b, typ):
    glColor(r, g, b)
    glBegin(typ)
    glVertex2d(x1, y1)
    glVertex2d(x2, y2)
    glVertex2d(x3, y3)
    glEnd()
def line(x, y, x1, y1, r, g, b, typ):
    glColor(r, g, b)
    glBegin(typ)
    glVertex2d(x,y)
    glVertex2d(x1, y1)
    glEnd()
def myInit():
      glMatrixMode(GL_PROJECTION)
      glClearColor(1, 1, 1, 1)
      glClear(GL_COLOR_BUFFER_BIT)
      #glOrtho(-10, 10,-10, 10, -10, 10)
      gluPerspective(50, 1, 0.1, 50)
      gluLookAt(10, 10, 10, 0, 0, 0, 0, 1, 0)
def draw_cube():
    glPushMatrix()
    glScale(2, 1, 1)
    glutWireCube(2)
    glPopMatrix()
def draw_chair():
    glPushMatrix()
    glScale(1, 0.25, 1)
    glutWireCube(4)
    glPopMatrix()
    glPushMatrix()
    glTranslate(0 , 2.5, -2)
    glScale(1, 1.5, 0.2)
    glutWireCube(4)
    glPopMatrix()
    glPushMatrix()
    glTranslate(1.875, -1, 1.875)
    glScale(1, 12, 1)
    glutWireCube(0.25)
    #glLoadIdentity()
    glPopMatrix()
    glPushMatrix()
    glTranslate(1.875, -1, -1.875)
    glScale(1, 12, 1)
    glutWireCube(0.25)
    #glLoadIdentity()
    glPopMatrix()
    glPushMatrix()
    glTranslate(-1.875, -1, 1.875)
    glScale(1, 12, 1)
    glutWireCube(0.25)
    #glLoadIdentity()
    glPopMatrix()
    glPushMatrix()
    glTranslate(-1.875, -1, -1.875)
    glScale(1, 12, 1)
    glutWireCube(0.25)
    glPopMatrix()
def draw():

    glClearColor(0, 1, 0, 1)
    glClear(GL_COLOR_BUFFER_BIT)
    glMatrixMode(GL_MODELVIEW)
    glLoadIdentity()
    glTranslate(-8, 0, 0)
    glColor3f(1, 0, 0)
    draw_chair()
    glTranslate(8, 0, 0)
    glColor3f(0, 0, 1)
    draw_chair()
    glFlush()

glutInit()
glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB| GLUT_DEPTH)
glutCreateWindow(b"Sec7")
glutInitWindowSize(100, 100)
glutDisplayFunc(draw)
#glutIdleFunc(draw)
myInit()
glutMainLoop()
